# code: language=ansible
---

- name: Add Trento agent repository
  community.general.zypper_repository:
    name: trento
    repo: "{{ trento_repository }}"
    state: present
    auto_import_keys: true

- name: Install Trento agent
  community.general.zypper:
    name: trento-agent
    state: latest

- name: Configure Trento agent
  ansible.builtin.template:
    src: "agent.conf.j2"
    dest: "/etc/trento/agent.yaml"
    mode: "0600"
  vars:
    server_url: "{{ trento_server_url }}"
    api_key: "{{ trento_api_key }}"
    facts_service_url: "amqp://{{ rabbitmq_username }}:{{ rabbitmq_password }}@{{ rabbitmq_host }}"
  notify:
    - Restart Trento agent

- name: Start Trento agent service
  ansible.builtin.service:
    name: trento-agent
    state: started
    enabled: true
