# code: language=ansible
---
- name: Install thirdparties
  hosts: trento-server
  become: true
  tasks:
   - name: Install installation prerequisites
     community.general.zypper:
      name:
       - gcc
       - python3-devel
       - sudo

   - name: Install python prerequisites
     community.general.zypper:
      name:
       - python3-setuptools
       - python3-pip
      state: present
      update_cache: true

   - name: Install docker
     community.general.zypper:
      name: docker
      state: present
      update_cache: true

   - name: Start docker service
     ansible.builtin.service:
      name: docker
      state: started
      enabled: true

- name: Configure trento projects
  vars:
   provision_postgres: "true"
   provision_rabbitmq: "true"
   provision_proxy: "true"
  hosts: trento-server
  become: true
  roles:
   - role: postgres
     when: provision_postgres == 'true'
     become: true
   - role: rabbitmq
     when: provision_rabbitmq == 'true'
     become: true
   - role: grafana
     become: true
   - role: containers
     become: true
   - role: proxy
     when: provision_proxy == 'true'
     become: true

- name: Configure trento agents
  hosts: agents
  become: true
  roles:
   - role: agent
     become: true
