# code: language=ansible
---
- name: Install erlang
  community.general.zypper:
    name: erlang
    state: present
    update_cache: true

- name: Install rabbitmq
  community.general.zypper:
    name: rabbitmq-server
    state: present
    update_cache: true

- name: Start rabbitmq service
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Create rabbitmq trento vhost
  community.rabbitmq.rabbitmq_vhost:
    name: "{{ rabbitmq_vhost }}"
    node: "{{ rabbitmq_node_name }}"
    state: present

- name: Configure rabbitmq trento user
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_username }}"
    node: "{{ rabbitmq_node_name }}"
    password: "{{ rabbitmq_password }}"
    permissions:
      - vhost: "{{ rabbitmq_vhost }}"
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
