# code: language=ansible
---
- name: Include RPM installation vars
  include_vars: "../defaults/install_rpm.yml"

- name: Create secrets
  no_log: true
  ansible.builtin.set_fact: # noqa: var-naming[no-jinja]
    "{{ item }}": "{{ lookup('community.general.random_string', base64=True, length=64) }}"
  when: lookup('vars', item) == ""
  loop:
    - secret_key_base
    - access_token_secret
    - refresh_token_secret

- name: Install trento-web
  community.general.zypper:
    name:
      - trento-web
      - trento-wanda
    state: present
    update_cache: true

- name: Print all available facts
  ansible.builtin.debug:
    var: hostvars

- name: Configure trento-web config
  ansible.builtin.template:
    src: trento-web.j2
    dest: /etc/trento/trento-web
    owner: root
    group: root
    mode: '0644'

- name: Configure trento-wanda config
  ansible.builtin.template:
    src: trento-wanda.j2
    dest: /etc/trento/trento-wanda
    owner: root
    group: root
    mode: '0644'

- name: Start trento-web service
  ansible.builtin.service:
    name: trento-web
    state: started
    enabled: true

- name: Start trento-wanda service
  ansible.builtin.service:
    name: trento-wanda
    state: started
    enabled: true
