# code: language=ansible
---
- name: Include RPM installation vars
  ansible.builtin.include_vars: "../defaults/rpm.yml"

- name: Install trento-web
  community.general.zypper:
    name:
      - trento-web
      - trento-wanda
    state: present
    update_cache: true

- name: Configure trento-web config
  ansible.builtin.template:
    src: trento-web.j2
    dest: /etc/trento/trento-web
    owner: root
    group: root
    mode: '0644'

- name: Configure trento-wanda config
  ansible.builtin.template:
    src: trento-wanda.j2
    dest: /etc/trento/trento-wanda
    owner: root
    group: root
    mode: '0644'

- name: Start trento-web service
  ansible.builtin.service:
    name: trento-web
    state: started
    enabled: true

- name: Start trento-wanda service
  ansible.builtin.service:
    name: trento-wanda
    state: started
    enabled: true
