# code: language=ansible
---
- name: Stop wanda container
  community.docker.docker_container:
    name: "{{ wanda_container_name }}"
    state: absent
    keep_volumes: false

- name: Stop web container
  community.docker.docker_container:
    name: "{{ web_container_name }}"
    state: absent
    keep_volumes: false

- name: Remove wanda container image
  community.docker.docker_image:
    state: absent
    name: "{{ wanda_container_image }}"

- name: Remove web container image
  community.docker.docker_image:
    state: absent
    name: "{{ web_container_image }}"

- name: Remove trento docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: absent
    force: true
