# code: language=ansible
---
- name: Disable and stop trento-web service
  ansible.builtin.service:
    name: trento-web
    state: stopped
    enabled: false

- name: Disable and stop trento-wanda service
  ansible.builtin.service:
    name: trento-wanda
    state: stopped
    enabled: false
