# code: language=ansible
---
- name: Close prometheus port using firewalld
  ansible.posix.firewalld:
    port: "{{ prometheus_port }}/tcp"
    permanent: true
    state: disabled
    offline: true
  when: firewalld_installed
  notify:
    - Restart firewalld if running
