# code: language=ansible
---
- name: Ensure prometheus group is present
  ansible.builtin.group:
    name: prometheus
    system: true
  when: ansible_distribution_version >= "15.4"

- name: Create Prometheus system user
  ansible.builtin.user:
    name: prometheus
    system: true
    group: prometheus
    shell: /sbin/nologin
    comment: "User for Prometheus service"
  when: ansible_distribution_version >= "15.4"

- name: Install package manually using expect module
  ansible.builtin.expect:
    command: zypper install golang-github-prometheus-prometheus
    responses:
      (?i)Choose from above solutions by number or cancel: "2"
      (?i)Continue?: "y"
  when: ansible_distribution_version >= "15.4"

- name: Install package using zypper module
  ansible.builtin.package:
    name: golang-github-prometheus-prometheus
    state: present
  when: ansible_distribution_version is version('15.4', '<')

- name: Enable prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Check the status of firewalld
  ansible.builtin.systemd:
    name: firewalld.service
  register: firewalld_status

- name: Open prometheus port using firewalld
  ansible.posix.firewalld:
    port: "{{ prometheus_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
    offline: true
  when: firewalld_status.status.ActiveState == "active"
