# code: language=ansible
---
- name: Restart firewalld if running
  ansible.builtin.service:
    name: firewalld
    state: restarted
  when: firewalld_status.status.ActiveState == "active"

- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted
